In [1]:
!pip install lightgbm

Requirement already satisfied: lightgbm in c:\anaconda3\lib\site-packages (4.6.0)
Requirement already satisfied: numpy>=1.17.0 in c:\anaconda3\lib\site-packages (from lightgbm) (1.26.4)
Requirement already satisfied: scipy in c:\anaconda3\lib\site-packages (from lightgbm) (1.13.1)

In [2]:
import pandas as pd

In [3]:
dataset = pd.read_csv("50_Startups.csv")

In [4]:
dataset

    R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87        127716.82  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08       110594.11        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida  141585.52
13   91992.39       135495.07        252664.93  California  134307.35
14  119943.24       156547.42        256512.92     Florida  132602.65
15  114523.61       122616.84        261776.23    New York  129917.04
16   78013.11       121597.55        264346.06  California  126992.93
17   94657.16       145077.58        282574.31    New York  125370.37
18   91749.16       114175.79        294919.57     Florida  124266.90
19   86419.70       153514.11             0.00    New York  122776.86
20   76253.86       113867.30        298664.47  California  118474.03
21   78389.47       153773.43        299737.29    New York  111313.02
22   73994.56       122782.75        303319.26     Florida  110352.25
23   67532.53       105751.03        304768.73     Florida  108733.99
24   77044.01        99281.34        140574.81    New York  108552.04
25   64664.71       139553.16        137962.62  California  107404.34
26   75328.87       144135.98        134050.07     Florida  105733.54
27   72107.60       127864.55        353183.81    New York  105008.31
28   66051.52       182645.56        118148.20     Florida  103282.38
29   65605.48       153032.06        107138.38    New York  101004.64
30   61994.48       115641.28         91131.24     Florida   99937.59
31   61136.38       152701.92         88218.23    New York   97483.56
32   63408.86       129219.61         46085.25  California   97427.84
33   55493.95       103057.49        214634.81     Florida   96778.92
34   46426.07       157693.92        210797.67  California   96712.80
35   46014.02        85047.44        205517.64    New York   96479.51
36   28663.76       127056.21        201126.82     Florida   90708.19
37   44069.95        51283.14        197029.42  California   89949.14
38   20229.59        65947.93        185265.10    New York   81229.06
39   38558.51        82982.09        174999.30  California   81005.76
40   28754.33       118546.05        172795.67  California   78239.91
41   27892.92        84710.77        164470.71     Florida   77798.83
42   23640.93        96189.63        148001.11  California   71498.49
43   15505.73       127382.30         35534.17    New York   69758.98
44   22177.74       154806.14         28334.72  California   65200.33
45    1000.23       124153.04          1903.93    New York   64926.08
46    1315.46       115816.21        297114.46     Florida   49490.75
47       0.00       135426.92             0.00  California   42559.73
48     542.05        51743.15             0.00    New York   35673.41
49       0.00       116983.80         45173.06  California   14681.40

In [5]:
dataset = pd.get_dummies(dataset,drop_first=True)

In [6]:
dataset

,R&D Spend,Administration,Marketing Spend,Profit,State_Florida,State_New York
0,165349.20,136897.80,471784.10,192261.83,False,True
1,162597.70,151377.59,443898.53,191792.06,False,False
2,153441.51,101145.55,407934.54,191050.39,True,False
3,144372.41,118671.85,383199.62,182901.99,False,True
4,142107.34,91391.77,366168.42,166187.94,True,False
5,131876.90,99814.71,362861.36,156991.12,False,True
6,134615.46,147198.87,127716.82,156122.51,False,False
7,130298.13,145530.06,323876.68,155752.60,True,False
8,120542.52,148718.95,311613.29,152211.77,False,True
9,123334.88,108679.17,304981.62,149759.96,False,False
10,101913.08,110594.11,229160.95,146121.95,True,False
11,100671.96,91790.61,249744.55,144259.40,False,False
12,93863.75,127320.38,249839.44,141585.52,True,False
13,91992.39,135495.07,252664.93,134307.35,False,False
14,119943.24,156547.42,256512.92,132602.65,True,False
15,114523.61,122616.84,261776.23,129917.04,False,True
16,78013.11,121597.55,264346.06,126992.93,False,False
17,94657.16,145077.58,282574.31,125370.37,False,True
18,91749.16,114175.79,294919.57,124266.90,True,False
19,86419.70,153514.11,0.00,122776.86,False,True
20,76253.86,113867.30,298664.47,118474.03,False,False
21,78389.47,153773.43,299737.29,111313.02,False,True
22,73994.56,122782.75,303319.26,110352.25,True,False
23,67532.53,105751.03,304768.73,108733.99,True,False
24,77044.01,99281.34,140574.81,108552.04,False,True
25,64664.71,139553.16,137962.62,107404.34,False,False
26,75328.87,144135.98,134050.07,105733.54,True,False
27,72107.60,127864.55,353183.81,105008.31,False,True
28,66051.52,182645.56,118148.20,103282.38,True,False
29,65605.48,153032.06,107138.38,101004.64,False,True
30,61994.48,115641.28,91131.24,99937.59,True,False
31,61136.38,152701.92,88218.23,97483.56,False,True
32,63408.86,129219.61,46085.25,97427.84,False,False
33,55493.95,103057.49,214634.81,96778.92,True,False
34,46426.07,157693.92,210797.67,96712.80,False,False
35,46014.02,85047.44,205517.64,96479.51,False,True
36,28663.76,127056.21,201126.82,90708.19,True,False
37,44069.95,51283.14,197029.42,89949.14,False,False
38,20229.59,65947.93,185265.10,81229.06,False,True
39,38558.51,82982.09,174999.30,81005.76,False,False
40,28754.33,118546.05,172795.67,78239.91,False,False
41,27892.92,84710.77,164470.71,77798.83,True,False
42,23640.93,96189.63,148001.11,71498.49,False,False
43,15505.73,127382.30,35534.17,69758.98,False,True
44,22177.74,154806.14,28334.72,65200.33,False,False
45,1000.23,124153.04,1903.93,64926.08,False,True
46,1315.46,115816.21,297114.46,49490.75,True,False
47,0.00,135426.92,0.00,42559.73,False,False
48,542.05,51743.15,0.00,35673.41,False,True
49,0.00,116983.80,45173.06,14681.40,False,False

In [7]:
dataset.columns

Index(['R&D Spend', 'Administration', 'Marketing Spend', 'Profit',
       'State_Florida', 'State_New York'],
      dtype='object')

In [8]:
independent=dataset[['R&D Spend', 'Administration', 'Marketing Spend','State_Florida', 'State_New York' ]]

In [9]:
independent

    R&D Spend  Administration  Marketing Spend  State_Florida  State_New York
0   165349.20       136897.80        471784.10          False            True
1   162597.70       151377.59        443898.53          False           False
2   153441.51       101145.55        407934.54           True           False
3   144372.41       118671.85        383199.62          False            True
4   142107.34        91391.77        366168.42           True           False
5   131876.90        99814.71        362861.36          False            True
6   134615.46       147198.87        127716.82          False           False
7   130298.13       145530.06        323876.68           True           False
8   120542.52       148718.95        311613.29          False            True
9   123334.88       108679.17        304981.62          False           False
10  101913.08       110594.11        229160.95           True           False
11  100671.96        91790.61        249744.55          False           False
12   93863.75       127320.38        249839.44           True           False
13   91992.39       135495.07        252664.93          False           False
14  119943.24       156547.42        256512.92           True           False
15  114523.61       122616.84        261776.23          False            True
16   78013.11       121597.55        264346.06          False           False
17   94657.16       145077.58        282574.31          False            True
18   91749.16       114175.79        294919.57           True           False
19   86419.70       153514.11             0.00          False            True
20   76253.86       113867.30        298664.47          False           False
21   78389.47       153773.43        299737.29          False            True
22   73994.56       122782.75        303319.26           True           False
23   67532.53       105751.03        304768.73           True           False
24   77044.01        99281.34        140574.81          False            True
25   64664.71       139553.16        137962.62          False           False
26   75328.87       144135.98        134050.07           True           False
27   72107.60       127864.55        353183.81          False            True
28   66051.52       182645.56        118148.20           True           False
29   65605.48       153032.06        107138.38          False            True
30   61994.48       115641.28         91131.24           True           False
31   61136.38       152701.92         88218.23          False            True
32   63408.86       129219.61         46085.25          False           False
33   55493.95       103057.49        214634.81           True           False
34   46426.07       157693.92        210797.67          False           False
35   46014.02        85047.44        205517.64          False            True
36   28663.76       127056.21        201126.82           True           False
37   44069.95        51283.14        197029.42          False           False
38   20229.59        65947.93        185265.10          False            True
39   38558.51        82982.09        174999.30          False           False
40   28754.33       118546.05        172795.67          False           False
41   27892.92        84710.77        164470.71           True           False
42   23640.93        96189.63        148001.11          False           False
43   15505.73       127382.30         35534.17          False            True
44   22177.74       154806.14         28334.72          False           False
45    1000.23       124153.04          1903.93          False            True
46    1315.46       115816.21        297114.46           True           False
47       0.00       135426.92             0.00          False           False
48     542.05        51743.15             0.00          False            True
49       0.00       116983.80         45173.06          False           False

In [10]:
dependent=dataset[['Profit']]

In [11]:
dependent

       Profit
0   192261.83
1   191792.06
2   191050.39
3   182901.99
4   166187.94
5   156991.12
6   156122.51
7   155752.60
8   152211.77
9   149759.96
10  146121.95
11  144259.40
12  141585.52
13  134307.35
14  132602.65
15  129917.04
16  126992.93
17  125370.37
18  124266.90
19  122776.86
20  118474.03
21  111313.02
22  110352.25
23  108733.99
24  108552.04
25  107404.34
26  105733.54
27  105008.31
28  103282.38
29  101004.64
30   99937.59
31   97483.56
32   97427.84
33   96778.92
34   96712.80
35   96479.51
36   90708.19
37   89949.14
38   81229.06
39   81005.76
40   78239.91
41   77798.83
42   71498.49
43   69758.98
44   65200.33
45   64926.08
46   49490.75
47   42559.73
48   35673.41
49   14681.40

In [12]:
from sklearn.model_selection import train_test_split   # import the library which is used for regression calculations
# Splitting and savinvg the training input and test values
# X_train - input train data
# X_test - input test data
# Y_train - output train data
# Y_test - output test data

X_train,X_test,Y_train,Y_test=train_test_split(independent,dependent,test_size=0.30,random_state=0)

In [13]:
from lightgbm import LGBMRegressor
import lightgbm as lgb


lgb_train = lgb.Dataset(X_train,Y_train )
lgb_eval = lgb.Dataset(X_test,Y_test, reference=lgb_train )
params = { 'boosting_type': 'gbdt',
          'objective': 'regression',
          'num_leaves': 20,
          'learning_rate': 0.1,
          'feature_fraction': 0.9   
}

gbm = lgb.train(params, lgb_train, num_boost_round=20, valid_sets=[lgb_train, lgb_eval], valid_names=['train','valid'], callbacks=[lgb.early_stopping(10)])

[LightGBM] [Warning] There are no meaningful features which satisfy the provided configuration. Decreasing Dataset parameters min_data_in_bin or min_data_in_leaf and re-constructing Dataset might resolve this warning.
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Total Bins 0
[LightGBM] [Info] Number of data points in the train set: 35, number of used features: 0
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Start training from score 110225.320145
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
Training until validation scores don't improve for 10 rounds
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements
Early stopping, best iteration is:
[1]	train's l2: 1.8501e+09	valid's l2: 1.00074e+09

In [14]:
# predictions

Y_pred = gbm.predict(X_test, gbm.best_iteration)

y_pred_binary = [1 if x > 0.5 else 0 for x in Y_pred]

Y_pred

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(Y_test, y_pred_binary)
accuracy

ValueError: Classification metrics can't handle a mix of continuous and binary targets